fastlane_version "2.81.0"

default_platform :mac

platform :mac do

  lane :send_coverage do
    scan(
      scheme: "note-Package",
      code_coverage: true,
      destination: 'arch=x86_64'
    )
    slather(
      proj: "note.xcodeproj",
      scheme: "note-Package",
      travis: true,
      source_directory: "Sources",
      output_directory: "report",
      ignore: [".build/*", "Tests/*"]
    )
  end
  
end
