fastlane_version "2.81.0"

default_platform :mac

platform :mac do

  lane :send_coverage do
    scan(
      scheme: "yubatake-Package",
      code_coverage: true,
      destination: 'arch=x86_64'
    )
    slather(
      proj: "yubatake.xcodeproj",
      scheme: "yubatake-Package",
      travis: true,
      binary_basename: "App",
      ignore: [".build/*", "Tests/*"],
      coveralls: true
    )
  end

  lane :dump_schema do
    sh("bundle exec ridgepole -c ../database.yml --export --output ../Schemafile")
  end

end
